name: aidocsagent
channels:
  - conda-forge
dependencies:
  - aiohttp=3.8.4=py310h8d17308_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - anyio=3.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h8d17308_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2023.5.7=h56e8100_0
  - certifi=2023.5.7=pyhd8ed1ab_0
  - cffi=1.15.1=py310h628cb3f_3
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=win_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.1.0=py310h232114e_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h00ffb61_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - docx2txt=0.8=py_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - exceptiongroup=1.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - fonttools=4.40.0=py310h8d17308_0
  - freetype=2.12.1=h546665d_1
  - frozenlist=1.3.3=py310h8d17308_0
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.31=pyhd8ed1ab_0
  - greenlet=2.0.2=py310h00ffb61_1
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.23.1=pyh025b116_0
  - ipython=8.14.0=pyh08f2357_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py310h5588dad_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.6.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h232114e_1
  - langchain=0.0.190=pyhd8ed1ab_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libabseil=20230125.2=cxx17_h63175ca_2
  - libblas=3.9.0=5_hd5c7e75_netlib
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libdeflate=1.18=hcfcfb64_0
  - libffi=3.4.2=h8ffe710_5
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libpng=1.6.39=h19919ed_0
  - libprotobuf=4.23.2=h1975477_5
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.42.0=hcfcfb64_0
  - libtiff=4.5.1=h6c8260b_0
  - libwebp-base=1.3.0=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libzlib=1.2.13=hcfcfb64_5
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.1.3=py310h8d17308_0
  - marshmallow=3.19.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib-base=3.7.1=py310h51140c5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.4=py310h8d17308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclassic=1.0.0=pyhb4ecaf3_1
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.5.0=pyhd8ed1ab_0
  - nbconvert-core=7.5.0=pyhd8ed1ab_0
  - nbconvert-pandoc=7.5.0=pyhd8ed1ab_0
  - nbformat=5.9.0=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - nomkl=1.0=h5ca1d4c_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numexpr=2.8.4=py310hc0342c8_100
  - openai=0.27.8=pyhd8ed1ab_0
  - openapi-schema-pydantic=1.2.4=pyhd8ed1ab_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openpyxl=3.1.2=py310h8d17308_0
  - openssl=3.1.1=hcfcfb64_1
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas-stubs=2.0.2.230605=pyhd8ed1ab_2
  - pandoc=3.1.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py310hb653ca7_1
  - pip=23.1.2=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.5.3=pyhd8ed1ab_0
  - plotly=5.15.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.17.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py310h8d17308_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.10.9=py310h8d17308_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pypdf=3.9.1=pyhd8ed1ab_0
  - pyrsistent=0.19.3=py310h8d17308_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.10.11=h4de0772_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-dotenv=1.0.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.17.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2023.3=pyhd8ed1ab_0
  - pywin32=304=py310h00ffb61_2
  - pywinpty=2.0.10=py310h00ffb61_0
  - pyyaml=6.0=py310h8d17308_5
  - pyzmq=25.1.0=py310hcd737a0_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - scikit-learn=1.2.2=py310hd266714_2
  - scipy=1.10.1=py310h578b7cb_3
  - send2trash=1.8.2=pyh08f2357_0
  - sentry-sdk=1.21.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py310h8d17308_1
  - setuptools=67.7.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlalchemy=2.0.16=py310h8d17308_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - stringcase=1.2.0=py_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.15.0=py310h5588dad_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - tornado=6.3.2=py310h8d17308_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - types-pytz=2023.3.0.0=pyhd8ed1ab_0
  - typing-extensions=4.6.3=hd8ed1ab_0
  - typing_extensions=4.6.3=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py310h8d17308_0
  - urllib3=2.0.3=pyhd8ed1ab_0
  - vc=14.3=hb25d44b_16
  - vc14_runtime=14.34.31931=h5081d32_16
  - vs2015_runtime=14.34.31931=hed1258a_16
  - wandb=0.15.4=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.0=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.9.2=py310h8d17308_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zstd=1.5.2=h12be248_6
  - pip:
      - altair==5.0.1
      - argilla==1.10.0
      - backoff==2.2.1
      - blinker==1.6.2
      - cachetools==5.3.1
      - chardet==5.1.0
      - commonmark==0.9.1
      - cryptography==41.0.1
      - deprecated==1.2.14
      - filetype==1.2.0
      - h11==0.14.0
      - httpcore==0.16.3
      - httpx==0.23.3
      - lxml==4.9.2
      - markdown==3.4.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - monotonic==1.6
      - msg-parser==1.2.0
      - nltk==3.8.1
      - numpy==1.23.5
      - olefile==0.46
      - pandas==1.5.3
      - pdf2image==1.16.3
      - pdfminer-six==20221105
      - protobuf==4.23.3
      - pyarrow==12.0.1
      - pydeck==0.8.1b0
      - pympler==1.0.1
      - pypandoc==1.11
      - python-docx==0.8.11
      - python-magic==0.4.27
      - python-pptx==0.6.21
      - pytz-deprecation-shim==0.1.0.post0
      - regex==2023.6.3
      - rfc3986==1.5.0
      - rich==13.0.1
      - smmap==5.0.0
      - streamlit==1.23.1
      - tabulate==0.9.0
      - tiktoken==0.4.0
      - toml==0.10.2
      - toolz==0.12.0
      - typer==0.9.0
      - tzlocal==4.3
      - unstructured==0.7.6
      - validators==0.20.0
      - watchdog==3.0.0
      - wrapt==1.14.1
      - xlrd==2.0.1
      - xlsxwriter==3.1.2